// languages/sample.jsx
// React: an orders table with a filter, hooks and a small child component.
import { useMemo, useState } from "react";

const money = (n) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(n);

function StatusBadge({ status }) {
  const tone = status === "paid" ? "ok" : status === "cancelled" ? "bad" : "muted";
  return <span className={`badge badge-${tone}`}>{status}</span>;
}

export default function Orders({ orders = [] }) {
  const [query, setQuery] = useState("");
  const visible = useMemo(
    () => orders.filter((o) => String(o.number).includes(query) || o.status.includes(query)),
    [orders, query]
  );

  if (orders.length === 0) return <p className="muted">No orders yet.</p>;

  return (
    <>
      <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter…" />
      <table>
        <tbody>
          {visible.map((o) => (
            <tr key={o.id}>
              <td>#{o.number}</td>
              <td>{money(o.total)}</td>
              <td><StatusBadge status={o.status} /></td>
            </tr>
          ))}
        </tbody>
      </table>
      <p>{visible.length} of {orders.length}</p>
    </>
  );
}

// languages/sample.vue
<script setup lang="ts">
// Vue 3: an orders table with a filter and a computed list.
import { computed, ref } from "vue";
import StatusBadge from "./StatusBadge.vue";

type Order = { id: string; number: number; total: number; status: string };
const props = defineProps<{ orders: Order[] }>();
const query = ref("");
const visible = computed(() => props.orders.filter((o) => String(o.number).includes(query.value)));
const money = (n: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(n);
</script>

<template>
  <h1>Orders</h1>
  <input v-model="query" placeholder="Filter…" />
  <p v-if="orders.length === 0" class="muted">No orders yet.</p>
  <table v-else>
    <tr v-for="order in visible" :key="order.id" :class="{ paid: order.status === 'paid' }">
      <td>#{{ order.number }}</td>
      <td>{{ money(order.total) }}</td>
      <td><StatusBadge :status="order.status" /></td>
    </tr>
  </table>
  <p>{{ visible.length }} of {{ orders.length }}</p>
</template>

<style scoped>
.muted { color: #888; }
tr.paid td { color: #2a7; }
</style>
